### ISSUE TITLE
请问能支持cdn后获取正确的用户ip不？

### ISSUE THREAD

**Issue by sixgodfan** [zwczou/lua-waf#1]
1.请问能支持cdn后获取正确的用户ip不？  
2.ip黑名单支持封禁ip6不？支持网段不如123.3.0.0/16等不，谢谢

**Comment by zwczou** [comment]
1.请问能支持cdn后获取正确的用户ip不？

> 是指通过头部获取IP么（比如常用的X-Real-Ip)

2. 支持网段的跟ipv6，因为是使用`resty.ipmatcher`来匹配网段的, 需要用`openresty`的`opm`安装 
3. 
`opm get xiangnanscu/lua-resty-ipmatcher`

**Comment by zwczou** [comment]
问题一，可以改这个地方`188-189`两行；
可以改成 
```lua
client_ip = ngx.req.get_headers()['X-Real-Ip']
key = client_ip 
```

`key = client_ip` 也带来了一些问题，比如，key更大了，shared_dict可能需要分配更大的空间


https://github.com/zwczou/lua-waf/blob/61ed67f0fc62ce18eb16507b78729ce126c49e0b/lib/waf/waf.lua#L188-L195
